#!/usr/bin/env perl

if ($#ARGV >= 0 && $argv[0] eq "-help") {
  print "usage: $0 infile [-c]\n";
  print "-c will print the contig name\n";
  exit(0);
}
if ($#ARGV < 0) {
 $IN = STDIN;
}
else {
$infile = shift @ARGV;
$printContig = 0;
$minLength = -1;
if ($#ARGV >= 0) {
  $opt = shift @ARGV;
  if ($opt eq "-c") {
    $printContig = 1;
  }
  if ($opt eq "-minLength") {
    $minLength = shift @ARGV;
  }
}
$minLength = 100;
open($IN, "$infile") or die "cannot open $infile\n";
}

$contigSize = -1;
$contig = "";
$first = 1;
while(<$IN>) {
  $line = $_;
  chomp($line);
  if (/^>/) {
    if ($first == 0) {
				if ($contigSize > 0 ) {
						if ($printContig == 1) {
								print "$contigSize $contig\n";
						} 
						else {
						  if ($minLength == -1 || $contigSize >= $minLength) {
						    print "$contigSize\n";
						  }
						}
				}
    }
    $first = 0;
    $contigSize = 0;
		$line =~ />(.*)/;
    $contig = $1;
  }
  else {
    $l = length($line);
    $contigSize += length($line);
  }
}

if ($contigSize > 0 ) {
  if ($printContig == 1) {
    print "$contig $contigSize\n";
  } 
  else {
    if ($minLength == -1 || $minLength <= $contigSize) {
    print "$contigSize\n";
  }
  }
}
