#!/usr/bin/env perl
@acs = ();
while ($#ARGV >= 0) {
		push @acs, shift @ARGV;
}

@cs = <>;
chomp @cs;
push @cs, @acs;
@css = sort {$a <=>$b} @cs;
$totSize = 0;
for ($i = 0; $i < @css; $i++) {
	$totSize = $totSize + @css[$i];
}

$cumSize = 0;
$n50 = -1;
for ($i = $#css; $i >= 0 && $n50 == -1; $i--) {
  $cumSize = $cumSize + @css[$i];
  if ($cumSize > ($totSize / 2)) {
     $n50 = $i;
  }
}

if ($n50 > -1) {
  print "@css[$n50]\n";
}
else {
  print "0\n";
}

