include ../common.mak

EXECS = csToDna
.PHONY: arch_dir $(EXECS)

all: $(CURDIR)/make.dep $(EXECS) 

include ../make.rules
include $(CURDIR)/make.dep

#csToDna: arch_dir $(MACHTYPE)/csToDna


LIBCOMMON = $(SRC_DIR)/lib/$(MACHTYPE)/libcommon.${LIB_EXT} 
LIBPB     = $(SRC_DIR)/lib/$(MACHTYPE)/libparseblast.${LIB_EXT} 


$(MACHTYPE)/csToDna: ${MACHTYPE}/CSToDNA.o ${MACHTYPE}/SOLiD.o
	$(CPP) $(CPPOPTS_lib) $(INCLUDEDIR) ${MACHTYPE}/SOLiD.o $< -o $@  $(LIBDIR) -lcommon $(LIBS)
