SRC=main.cpp graphConstruction.cpp pairedGraph.cpp simpleGraph.cpp parser.cpp constructHashTable.cpp seq.cpp sequence.cpp nucl.cpp parser.cpp graphVisualizer.cpp #pairedGraph.cpp main.cpp 
DIR=paireddebruijn
PROG=paireddebruijn

include ../makefile.inc
