SRC=test.cpp graphConstruction.cpp pairedGraph.cpp simpleGraph.cpp parser.cpp constructHashTable.cpp seq.cpp parser.cpp #pairedGraph.cpp main.cpp 
DIR=paireddebruijn
PROG=paireddebruijnTest

include ../makefile.inc

