SRC= graphConstruction.cpp pairedGraph.cpp simpleGraph.cpp main.cpp parser.cpp constructHashTable.cpp ../seq.cpp ../parser.cpp #pairedGraph.cpp main.cpp 
DIR=paireddebruijn
PROG=paireddebruijn

include ../makefile.inc

