#!/usr/bin/env perl
use POSIX;

if ($#ARGV != 2) {
  print "usage: Print name.rul cloneLength error readLength\n"; 
  exit(0);
}
$cloneLength = shift @ARGV;
$error = shift @ARGV;
$pctError = $error / 100;
$rl = shift @ARGV;
$dif = $cloneLength * $pctError;
$pctError = $error / 100;
$bottomEnd = POSIX::floor($cloneLength - $dif + ($rl * 2)); 
$topEnd    = POSIX::floor($cloneLength + $dif + ($rl * 2));
print "/*                      Names are: Library_Plate_well.primer\n";
print "                                primer  library plate   length range    */\n";
print "\n";
print "Single reads:                   s       ALL     ALL\n";
print "Double-barreled reads:          x y     ALL     ALL     $bottomEnd $topEnd\n";
print "Double-barreled reads:          b g     ALL     ALL     1500 3500\n";
