# -*- cmake -*-

set(CPACK_CMAKE_GENERATOR "Unix Makefiles")

# Binary stuff
set(CPACK_GENERATOR "TGZ")
set(CPACK_PACKAGE_NAME "${SPADES_FLAVOUR}")
set(CPACK_PACKAGE_VENDOR "SPAdes Team")
#set(CPACK_PACKAGE_DESCRIPTION_FILE "${SPADES_MAIN_SRC_DIR}/../README")
set(CPACK_RESOURCE_FILE_LICENSE "${SPADES_MAIN_SRC_DIR}/../LICENSE")
set(CPACK_PACKAGE_VERSION "${SPADES_PACKAGE_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${SPADES_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${SPADES_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${SPADES_VERSION_PATCH}")

# Source stuff
set(CPACK_SOURCE_GENERATOR "TBZ2")
set(CPACK_SOURCE_IGNORE_FILES tools test online_vis)
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")

include(CPack)
