#!/bin/bash

############################################################################
# Copyright (c) 2015 Saint Petersburg State University
# Copyright (c) 2011-2014 Saint Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################


if [ "$EDITOR" = "" ] ; then
  EDITOR=`git config --get core.editor`
fi
if [ "$EDITOR" = "" ] ; then
  EDITOR="vi"
fi

if [ $# = 0 ]
then
  set $1 'c'
fi

case $1 in
  'c')  cfg="configs/config.info" ;;
  's')  cfg="configs/simplification.info" ;;
  'de') cfg="configs/distance_estimation.info";;
  'dip') cfg="configs/detail_info_printer.info";;
  'log') cfg="configs/log.properties";;
  'pep')   cfg="configs/pe_params.info";;
  'con')   cfg="configs/construction.info";;
  
esac

$EDITOR $cfg
