#!/bin/bash

cp src/debruijn/config.info.template                src/debruijn/config.info
cp src/debruijn/simplification.info.template        src/debruijn/simplification.info
cp src/debruijn/distance_estimation.info.template   src/debruijn/distance_estimation.info

