#!/bin/bash

############################################################################
# Copyright (c) 2015 Saint Petersburg State University
# Copyright (c) 2011-2014 Saint Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################

cmd=cp
if [ $# = 0 ]
    then
        set 1 '-all'
fi

for arg; do
    if [ $arg = '-d' ]
        then
            cmd=diff
            if [ $# = 1 ]; then
                set 1 '-all' 
            fi
    fi
done

for arg; do

case $arg in
  'c')   $cmd configs/debruijn/config.info.template configs/debruijn/config.info ;;
  'h')   $cmd configs/hammer/config.info.template configs/hammer/config.info ;;  
  'ih')  $cmd configs/ionhammer/ionhammer.cfg.template configs/ionhammer/ionhammer.cfg ;;
  's')   $cmd configs/debruijn/simplification.info.template configs/debruijn/simplification.info ;;
  'de')  $cmd configs/debruijn/distance_estimation.info.template configs/debruijn/distance_estimation.info;;
  'dip') $cmd configs/debruijn/detail_info_printer.info.template configs/debruijn/detail_info_printer.info;;
  'log') $cmd configs/debruijn/log.properties.template configs/debruijn/log.properties ;;
  'sp')  $cmd spades_config.info.template spades_config.info;;
  'pep') $cmd configs/debruijn/path_extend/pe_params.info.template   configs/debruijn/path_extend/pe_params.info;;
  'con') $cmd configs/debruijn/construction.info.template   configs/debruijn/construction.info;;
  'ds') $cmd configs/dipspades/config.info.template configs/dipspades/config.info;;
  'tsa') $cmd configs/debruijn/tsa.info.template   configs/debruijn/tsa.info;;
  'logds') $cmd configs/dipspades/log.properties.template configs/dipspades/log.properties;;
  '-all')
		echo -----------------configs/debruijn/config.info-------------------
        $cmd configs/debruijn/config.info.template                  configs/debruijn/config.info
		echo ------------------configs/hammer/config.info--------------------
        $cmd configs/hammer/config.info.template                    configs/hammer/config.info
		echo -------------configs/debruijn/simplification.info---------------
        $cmd configs/debruijn/simplification.info.template          configs/debruijn/simplification.info
		echo -----------configs/debruijn/distance_estimation.info------------
        $cmd configs/debruijn/distance_estimation.info.template     configs/debruijn/distance_estimation.info
		echo -----------configs/debruijn/detail_info_printer.info------------
        $cmd configs/debruijn/detail_info_printer.info.template     configs/debruijn/detail_info_printer.info
		echo ----------------configs/debruijn/log.properties-----------------
        $cmd configs/debruijn/log.properties.template               configs/debruijn/log.properties
		echo ----------configs/debruijn/path_extend/pe_config.info-----------
        $cmd configs/debruijn/path_extend/pe_params.info.template   configs/debruijn/path_extend/pe_params.info
		echo --------------configs/debruijn/construction.info----------------
        $cmd configs/debruijn/construction.info.template   configs/debruijn/construction.info
		echo ------------------configs/dipspades/configs.info----------------
    	$cmd configs/dipspades/config.info.template	    configs/dipspades/config.info
                echo --------------------configs/dipspades/tsa.info------------------
        $cmd configs/debruijn/tsa.info.template   configs/debruijn/tsa.info
		echo ---------------configs/dipspades/log.properties-----------------
    	$cmd configs/dipspades/log.properties.template configs/dipspades/log.properties
		echo ---------------configs/ionhammer/ionhammer.cfg----------------
	$cmd configs/ionhammer/ionhammer.cfg.template configs/ionhammer/ionhammer.cfg 
               echo ---------------configs/corrector/corrector.info----------------
        $cmd configs/corrector/corrector.info.template configs/corrector/corrector.info
esac

done
