#!/bin/bash

if [ "$EDITOR" = "" ] ; then
  EDITOR=`git config --get core.editor`
fi
if [ "$EDITOR" = "" ] ; then
  EDITOR="vi"
fi

if [ $# = 0 ]
then
  set $1 'c'
fi

case $1 in
  'c')  cfg="src/debruijn/config.info" ;;
  'ct') cfg="src/debruijn/config.info.template" ;;
  's')  cfg="src/debruijn/simplification.info" ;;
  'st') cfg="src/debruijn/simplification.info.template" ;;
  'de') cfg="src/debruijn/distance_estimation.info";;
  'det') cfg="src/debruijn/distance_estimation.info.template";;
  'd')  cfg="src/debruijn/datasets.info" ;;
  'dip') cfg="src/debruijn/detail_info_printer.info";;
  'dipt') cfg="src/debruijn/detail_info_printer.info.template";;
esac

$EDITOR $cfg
