#!/bin/bash

if [ "$EDITOR" = "" ] ; then
  EDITOR=`git config --get core.editor`
fi
if [ "$EDITOR" = "" ] ; then
  EDITOR="vi"
fi

if [ $# = 0 ]
then
  set $1 'sp'
fi

case $1 in
  'c')  cfg="configs/debruijn/config.info" ;;
  'ct') cfg="configs/debruijn/config.info.template" ;;
  's')  cfg="configs/debruijn/simplification.info" ;;
  'st') cfg="configs/debruijn/simplification.info.template" ;;
  'de') cfg="configs/debruijn/distance_estimation.info";;
  'det') cfg="configs/debruijn/distance_estimation.info.template";;
  'd')  cfg="configs/debruijn/deprecated_datasets.info" ;;
  'da')  cfg="configs/debruijn/deprecated_datasets_archive.info" ;;
  'dip') cfg="configs/debruijn/detail_info_printer.info";;
  'dipt') cfg="configs/debruijn/detail_info_printer.info.template";;
  'log') cfg="log4cxx.properties";;
  'logt') cfg="log4cxx.properties.template";;
  'sp')   cfg="spades_config.info";;
  'spt')   cfg="spades_config.info.template";;
  
esac

$EDITOR $cfg
