#!/bin/bash

############################################################################
# Copyright (c) 2011-2012 Saint-Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################

cp src/include/k_range.hpp.template src/include/k_range.hpp

#BASE="$( cd "$( dirname "$0" )" && pwd )"
#FILE=$BASE/src/debruijn/k.hpp
#TMP=temp_$(date +%s)
#
#if [ $# = 0 ] ; then
#  echo "ERROR: K value should be specified as first parameter"
#  exit
#fi
#
#echo -e "#pragma once\n\nnamespace debruijn_graph {\n\tconst size_t K = "$1";\n}" > $TMP
#if [ -a $FILE ] && [ "$(diff -q $TMP $FILE)" == "" ] ; then
#  echo "K was already $1"
#  rm $TMP
#  exit
#fi
#
#mv $TMP $FILE
