#!/bin/bash
FILE=src/debruijn/k.hpp
TMP=temp_$(date +%m.%d_%H_%M)

if [ $# = 0 ] ; then
  echo "ERROR: K value should be specified as first parameter"
  exit
fi

echo -e "#pragma once\n\nnamespace debruijn_graph {\n\tconst size_t K = "$1";\n}" > $TMP
if [ "$(diff $TMP $FILE)" = "" ] ; then
  echo "K was already $1"
  exit
fi

mv $TMP $FILE
