#!/bin/bash

function iterative_run
{
	echo "$NAME started"

	for i in $*
	do

		echo "Generating k.hpp for K="$i
		./gen_k $i 

		echo "Compiling assembler for K="$i
		make rd

		echo "Running assembler for K="$i
		./run rd | tee $LOG_DIR/"K$i.log"

	done

	echo "$NAME finished"
}

START=$(date +%m.%d_%H.%M.%S)
LOG_DIR=logs/$START
NAME="Iterative run $START (K = $*)"
rm logs/latest
ln -s $START logs/latest
mkdir $LOG_DIR

iterative_run $* | tee $LOG_DIR/"overall.log"
tail $LOG_DIR/"overall.log" | mail -s "$NAME finished" $(git config --get user.email)
