.PHONY: dd rd

dd: 
	make -C build/debug/debruijn

rd:
	make -C build/release/debruijn

clean:
	make -C build/debug clean
	make -C build/release clean

#temporary fix
all: make -C build/release all


