#!/bin/bash

############################################################################
# Copyright (c) 2015 Saint Petersburg State University
# Copyright (c) 2011-2014 Saint Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################

set -e

export assembler="`pwd`"
export src="$assembler/src"
export ext="$assembler/ext"
export build="$assembler/build"

echo "/**************************************/"
echo "/********  preparing debug ************/"
echo "/**************************************/"

mkdir -p $build/debug
cd $build/debug
cmake $src -DCMAKE_BUILD_TYPE="Debug" -DSPADES_BUILD_INTERNAL=1

echo "/**************************************/"
echo "/********  preparing release **********/"
echo "/**************************************/"

mkdir -p $build/release
cd $build/release
cmake $src -DCMAKE_BUILD_TYPE="RelWithAsserts" -DSPADES_BUILD_INTERNAL=1
cd $assembler
