#!/bin/bash

############################################################################
# Copyright (c) 2011-2014 Saint-Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################


#renaming templates to originals
cp -n .project.template .project
cp -n .cproject.template .cproject

cd src/debruijn
#cp -n .project.template .project
#cp -n .cproject.template .cproject
cp -n "debruijn release.launch.template" "debruijn release.launch"
cp -n "debruijn debug.launch.template" "debruijn debug.launch"

cd ../abruijn
#cp -n .project.template .project
#cp -n .cproject.template .cproject
cp -n "abruijn release.launch.template" "abruijn release.launch"
cp -n "abruijn debug.launch.template" "abruijn debug.launch"

cd ../hammer
#cp -n .project.template .project
#cp -n .cproject.template .cproject
cp -n "hammer release.launch.template" "hammer release.launch"
cp -n "hammer debug.launch.template" "hammer debug.launch"

cd ../test/debruijn
cp -n "debruijn_test release.launch.template" "debruijn_test release.launch"
cp -n "debruijn_test debug.launch.template" "debruijn_test debug.launch"

cd ../include_test
cp -n "include_test release.launch.template" "include_test release.launch"
cp -n "include_test debug.launch.template" "include_test debug.launch"

# going to root folder (assembler)
cd ../../..

# preparing makefile for all projects and both configurations
rm -rf build/*
./prepare_cfg
