#!/bin/bash

############################################################################
# Copyright (c) 2011-2013 Saint-Petersburg Academic University
# All Rights Reserved
# See file LICENSE for details.
############################################################################

## reading output_base
read output_base <<< $(awk -v property="output_base" '{if ($1==property) print $2;}' configs/debruijn/config.info)
## creating output_base dir if not exists
mkdir -p $output_base
## copying configs to temporary dir inside output_base
tmp_cfg_dir="$output_base/tmp_configs"
mkdir -p $tmp_cfg_dir
cp -r configs $tmp_cfg_dir 
cfg_debruijn="$tmp_cfg_dir/configs/debruijn"

function run_n_measure
{
   if [ "$(uname -s)" == "Darwin" ]; then # Mac OS X
       /usr/bin/time $1 $2 $3 $4 $5 $6 $7
   else # other, e.g. Linux
       /usr/bin/time -f "\n\ntime: %E" $1 $2 $3 $4 $5 $6 $7
   fi
}

function change_config
{
    ds_folder="configs/debruijn/datasets/"
    dsa_folder="configs/debruijn/datasets_archive/"
    
    ds_folder_prefix=${ds_folder//\//\\\/}
    dsa_folder_prefix=${dsa_folder//\//\\\/}

    ls -t $ds_folder | sed -e "s/^/$ds_folder_prefix/" > temp
    ls -t $dsa_folder | sed -e "s/^/$dsa_folder_prefix/" >> temp
    
    #awk '/\{/ {print str} {str = $1}' configs/debruijn/datasets.info > temp
    #awk '/\{/ {print str} {str = $1}' configs/debruijn/datasets_archive.info >> temp

# firstly exact match

    dataset="`grep -w $1 temp`"
    if [ "{$dataset" == "{" ]; then
        dataset="`grep $1 temp`"
    fi
    if [ "{$dataset" == "{" ]; then
        echo "No dataset for you!"
        #rm temp
        exit
    fi
    if [ ` echo "$dataset" | sed -n '$='` == 1 ]; then
        filename=$(basename $dataset)
        filename=${filename%.*}
        echo "$filename dataset chosen"
        awk -v ds=$filename '{if ($1 == "project_name") print "project_name","\t",ds; else print $0}' $cfg_debruijn/config.info  > config1.info
        awk -v ds=$dataset '{if ($1 == "dataset") print "dataset","\t",ds; else print $0}' config1.info > config.info
        mv config.info $cfg_debruijn/config.info
        rm config1.info
    else
        echo "Dataset ambiguous :"
        echo "$dataset"
        echo "The first one will be chosen :"
        dataset=`echo $dataset | awk '{print $1}' `
        filename=$(basename $dataset)
        filename=${filename%.*}
        echo "$filename"
        awk -v ds=$filename '{if ($1 == "project_name") print "project_name","\t",ds; else print $0}' $cfg_debruijn/config.info  > config1.info
        awk -v ds=$dataset '{if ($1 == "dataset") print "dataset","\t",ds; else print $0}' config1.info  > config.info
        mv config.info $cfg_debruijn/config.info
        rm config1.info
    fi

    rm temp
}


#   awful, awful!
    awk -v property="run_mode" -v value="true"  '{if ($1==property) print property,value; else print $0}' $cfg_debruijn/config.info  > config1.info
    mv config1.info $cfg_debruijn/config.info
#   --------------------------------------------

if [ $# = 0 ]
then
    run_n_measure build/release/bin/spades $cfg_debruijn/config.info 
else 
    if [ $# = 2 ]
    then
        change_config $2
    fi

    case $1 in

    'rd' ) run_n_measure build/release/bin/spades $cfg_debruijn/config.info ;;
    'dd' ) run_n_measure build/debug/bin/spades $cfg_debruijn/config.info ;;
    'ddt' ) run_n_measure build/debug/bin/debruijn_test ;;
    'rdt' ) ./build/release/bin/debruijn_test --log_level=test_suite ;;
    'ddtls' ) run_n_measure build/debug/bin/debruijn_tools ;;
    'rdtls' ) run_n_measure build/release/bin/debruijn_tools ;;
    'dit' ) run_n_measure build/debug/bin/include_test ;;
    'dt') run_n_measure build/debug/bin/debruijn_test && run_n_measure build/debug/bin/include_test ;;
    'rv' ) build/release/bin/online_vis $cfg_debruijn/config.info ;;
    'dv' ) build/debug/bin/online_vis $cfg_debruijn/config.info ;;
    'rc' ) run_n_measure build/release/bin/cap --log_level=test_suite ;;
    'dc' ) run_n_measure build/debug/bin/cap --log_level=test_suite ;;
    'rct' ) run_n_measure build/release/bin/cap_test ;;
    'dct' ) run_n_measure build/debug/bin/cap_test ;;

    * ) 
        change_config $1

        run_n_measure build/release/bin/spades $cfg_debruijn/config.info ;;
        #run_n_measure $1 $2 $3 $4 $5 
    esac
fi

# clearing temporary configs dir
rm -r $tmp_cfg_dir
