/*
 * parserTest.hpp
 *
 *  Created on: 02.03.2011
 *      Author: vyahhi
 */

#include "cute.h"
#include "ireadstream.hpp"

void TestIReadStream() {
	ireadstream<100,2,short> irs("./test/data/s_6_1.fastq.gz", "./test/data/s_6_2.fastq.gz");
	strobe_read<100,2,short> sr;
	mate_read<100,short>::type mr;
	irs >> sr >> mr;
	ASSERT_EQUAL("CATTATTAGGGATGATTGTGACCCGCGTCAGACCAATCAAATTCGCCAGCGTTTCCACGGGTTTTAGATGACCATAGTGCACCGGATCAAAGGTGCCGCC", sr[0].str());
	ASSERT_EQUAL("ATTACGGTCAGTCAGTGTGGGCAGAGCTGGAAGGGTTATCTCTTCTGTTGTGCCATAAACCCCTGGCGGACGTATTTATCGACGGTTGATATGTAATCTT", sr[1].str());
	ASSERT_EQUAL("GCAGTAAAGCTATCATGGCAGAATCATTTGCAACTGGTTCCGATCATCAGGTTGTAAACGAGCTCAACGGGGAAAGACTGAGAGAACCAAACGACGTTTT", mr[0].str());
	ASSERT_EQUAL("GGCCAACGTTAATTTTGTTACCGACTAAAGTAGAAACTATTTCTTTTAGATGGTCGCATTTATATTTTGCATCGTCCACTTGAAAATCATATCTTATTGC", mr[1].str());
}

void TestIReadStreamFull() {
	ireadstream<100,2,short> irs("./test/data/s_6_1.fastq.gz", "./test/data/s_6_2.fastq.gz");
	mate_read<100,short>::type mr;
	while (!irs.eof()) {
		irs >> mr;
	}
	irs.close();
	ASSERT_EQUAL("CATACGGGTTTCCGCCAGTTTTTCCATGCCGCGATGGACGTAGAACAGACGGTAGTCGGCGTCGATAATGTTTTCGCCATCGACGCACAGACGGAAGTGG", mr[0].str());
	ASSERT_EQUAL("CGTCCGGCACCGACCACCGATGCTGAAACCTACGAGTTCATCAACGAACTGGGCGACAAGAAAAACAACGTCGTGCCGATTGGTCCGCTGCACGTCACTT", mr[1].str());

}

cute::suite IReadStreamSuite(){
	cute::suite s;
	s.push_back(CUTE(TestIReadStream));
	s.push_back(CUTE(TestIReadStreamFull));
	return s;
}
