include ../common.mak

EXECS = axtToLav
.PHONY: arch_dir  $(EXECS)

all: $(CURDIR)/make.dep  $(EXECS)

include ../make.rules
include $(CURDIR)/make.dep

axtTolav: arch_dir $(MACHTYPE)/axtTolav

$(MACHTYPE)/axtTolav: ${MACHTYPE}/axtTolav.o \
			   $(SRC_DIR)/lib/$(MACHTYPE)/libcommon.${LIB_EXT}	\
			   $(SRC_DIR)/lib/$(MACHTYPE)/libaxt.${LIB_EXT}	 \
			   $(SRC_DIR)/lib/$(MACHTYPE)/liblav.${LIB_EXT}	
	$(CPP) $(CPPOPTS_lib) $(INCLUDEDIR) $< -o $@  $(LIBDIR) -lcommon -laxt -llav $(LIBS)



