default:
	dot -Tpdf -o fig1.pdf fig1.dot
	dot -Tpdf -o fig2.pdf fig2.dot
	dot -Tpdf -o fig3.pdf fig3.dot
	dot -Tpdf -o fig4.pdf fig4.dot
	pdflatex abruijn
clean:
	rm abruijn.log abruijn.aux abruijn.pdf fig1.pdf fig2.pdf fig3.pdf fig4.pdf
