default:
	dot -Tpdf -O fig1.dot
	dot -Tpdf -O fig2.dot
	dot -Tpdf -O fig3.dot
	dot -Tpdf -O fig4.dot
	pdflatex abruijn
clean:
	rm abruijn.log abruijn.aux abruijn.pdf fig1.jpg fig2.jpg fig3.jpg fig4.jpg
