include ../common.mak

HEADERS    = $(TL_HEADERS) $(AL_HEADERS) 
# tune the compiler

LIBDEP = common align
LIBS  += $(addprefix -l, $(LIBDEP))

INV_OBJS = InversionChars.o ValidatedInversions.o
ARCH_OBJS  = $(addprefix $(MACHTYPE)/, $(INV_OBJS) $(OBJS))

#INCLUDEDIR += $(MYSQL_INC)
#CCOPTS += -Wno-long-double

#EXECS = loop winaln dbloop fog fsl findorder dblap storient etadilav  validphylo maketemp makeself  bininversions extinv  buildphylo

ifeq ($(MACHTYPE), x86_64)
EXECS =  buildphylo  makegrid phylotrek locator specinv ordient 
else
EXECS =  buildphylo cacy makegrid phylotrek extractloci locator filterbin findregion specinv ordient 
endif

all:    arch_dir $(CURDIR)/make.dep $(EXECS) install

.PHONY: arch_dir $(EXECS)


include ../make.rules
include $(CURDIR)/make.dep
specinv: $(MACHTYPE)/specinv
findregion: $(MACHTYPE)/findregion
extractloci: $(MACHTYPE)/extractloci
phylotrek: $(MACHTYPE)/phylotrek
locator: $(MACHTYPE)/locator
makegrid: $(MACHTYPE)/makegrid
extinv: $(MACHTYPE)/extinv
cacy: $(MACHTYPE)/cacy
bininversions: $(MACHTYPE)/bininversions
maketemp: $(MACHTYPE)/maketemp
makeself: $(MACHTYPE)/makeself
biscut: $(MACHTYPE)/biscut
filterbin: $(MACHTYPE)/filterbin
cfg: $(MACHTYPE)/cfg
buildphylo: $(MACHTYPE)/buildphylo
lia: $(MACHTYPE)/lia
fsl: $(MACHTYPE)/fsl
loop: $(MACHTYPE)/loop
#ncbiToSC: $(MACHTYPE)/ncbiToSC
winaln: $(MACHTYPE)/winaln
dbloop: $(MACHTYPE)/dbloop
dblap: $(MACHTYPE)/dblap
storient: $(MACHTYPE)/storient
fog: $(MACHTYPE)/fog
findorder: $(MACHTYPE)/findorder
ordient: $(MACHTYPE)/ordient
etadilav: $(MACHTYPE)/etadilav
validphylo: $(MACHTYPE)/validphylo

#ctree: $(MACHTYPE)/ctree

#grp: $(MACHTYPE)/grp

#%$(MACHTYPE)/ctree: $(MACHTYPE)/CharTree.o $(LIBCOMMON)
#	$(CC) $(CCOPTS) $< -o $@  $(LIBDIR) -lcommon  -lstdc++


$(MACHTYPE)/extractloci: $(MACHTYPE)/ExtractLoci.o $(MACHTYPE)/FragmentUtils.o \
	$(LIBCOMMON) $(LIBLAV) $(LIBNET)
	$(CC) $(CCOPTS) $^ -o $@ \
	$(LIBDIR) $(LIBS) -llav -lnet -lblocks -lm  

$(MACHTYPE)/phylotrek: $(MACHTYPE)/PhylogeneticTrek.o $(MACHTYPE)/FragmentUtils.o \
	$(LIBCOMMON) $(LIBLAV) $(LIBNET)
	$(CC) $(CCOPTS) $^ -o $@ \
	$(LIBDIR) $(LIBS) -llav -lblocks -lnet -lm  

$(MACHTYPE)/locator: $(MACHTYPE)/LocateFragments.o $(MACHTYPE)/FragmentUtils.o\
	$(LIBCOMMON) $(LIBNET) $(LIBLAV) 
	$(CC) $(CCOPTS) $^ -o $@ \
	$(LIBDIR) $(LIBS) -llav -lm  

$(MACHTYPE)/findregion: $(MACHTYPE)/FindRegion.o $(MACHTYPE)/FragmentUtils.o\
	$(LIBCOMMON) $(LIBNET) $(LIBLAV) 
	$(CC) $(CCOPTS) $^ -o $@ \
	$(LIBDIR) $(LIBS) -llav -lnet -lblocks -lm  

$(MACHTYPE)/specinv: $(MACHTYPE)/SpeciesInversions.o \
	$(LIBCOMMON)  \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/ValidatedInversion.o 
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(LIBDIR) $(LIBS)  -lemboss -lm -lstdc++ -lalign


$(MACHTYPE)/makegrid: $(MACHTYPE)/MakeGrid.o \
	$(LIBCOMMON)  $(LIBEMBOSS) $(LIBNET) $(LIBLAV) $(LIBALIGN)\
	$(MACHTYPE)/InversionBins.o $(MACHTYPE)/ShuffleAlign.o  \
	$(MACHTYPE)/ValidatedInversion.o
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/ShuffleAlign.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(LIBDIR) $(LIBS)  -lemboss -lm -lstdc++ -lalign



$(MACHTYPE)/extinv: $(MACHTYPE)/ExtractInversions.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionFile.o \
	$(MACHTYPE)/InversionBins.o $(LIBCOMMON)  $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBNET) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionFile.o \
	$(LIBDIR) $(LIBS) -lblockdb -lemboss -lnet -llav -lstdc++ 


$(MACHTYPE)/cacy: $(MACHTYPE)/CheckAlternatingCycles.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(MACHTYPE)/InversionBins.o $(LIBCOMMON)  $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBNET) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionUtils.o $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(LIBDIR) $(LIBS) -lemboss -lnet -llav -lstdc++ 

$(MACHTYPE)/bininversions: $(MACHTYPE)/BinInversionList.o \
	$(MACHTYPE)/InversionDB.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionBins.o  $(LIBCOMMON) $(LIBNET) $(LIBBLOCKDB)  $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionUtils.o $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionDB.o \
	$(LIBDIR) $(LIBS) \
	 -lblockdb -lnet -lemboss -llav $(MYSQL_LIB) -lstdc++ 

$(MACHTYPE)/maketemp: $(MACHTYPE)/MakeTemp.o  \
	$(MACHTYPE)/InversionUtils.o \0

	$(MACHTYPE)/InversionBins.o  $(LIBCOMMON) $(LIBNET) $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionUtils.o $(MACHTYPE)/InversionBins.o \
	 $(LIBDIR) $(LIBS) \
	 -lblockdb -lnet -lemboss -llav $(MYSQL_LIB) -lstdc++ 

$(MACHTYPE)/makeself: $(MACHTYPE)/MakeSelfTable.o  \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionBins.o  $(LIBCOMMON) $(LIBNET) $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ \
	$(MACHTYPE)/InversionUtils.o $(MACHTYPE)/InversionBins.o \
	 $(LIBDIR) $(LIBS) \
	 -lblockdb -lnet -lemboss -llav $(MYSQL_LIB) -lstdc++ 

$(MACHTYPE)/filterbin: $(MACHTYPE)/FilterBins.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(MACHTYPE)/FourGameteUtils.o $(LIBCOMMON) $(LIBNET) $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/FourGameteUtils.o  -o $@ $(LIBDIR) $(LIBS) -lnet -lblock -lemboss -llav  -lstdc++ 

$(MACHTYPE)/findcon: $(MACHTYPE)/FindConnections.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o $(LIBCOMMON) $(LIBNET) $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o   -o $@ $(LIBDIR) $(LIBS)  -lblockdb -lnet -lemboss -llav $(MYSQL_LIB) -lstdc++ 


$(MACHTYPE)/cfg: $(MACHTYPE)/CheckFourGametes.o $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/FourGameteUtils.o  $(LIBCOMMON) $(LIBNET) $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/FourGameteUtils.o \
	 -o $@ $(LIBDIR) $(LIBS) -lnet -lemboss -llav -lstdc++ 

$(MACHTYPE)/validphylo:	$(MACHTYPE)/ValidateInversionPhylogeny.o  \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/CharTree.o $(MACHTYPE)/InversionBins.o $(LIBCOMMON) $(LIBBLOCKDB) $(LIBNET) $(LIBTREE) $(LIBEMBOSS) $(ARCH_ORTHOBJS) $(LIBLAV)
	$(CC) $(CCOPTS) $<  \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o -o $@ $(LIBDIR) $(LIBS) -lnet -ltree -lemboss -llav -lstdc++



$(MACHTYPE)/buildphylo: $(MACHTYPE)/BuildPhylogeny.o \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/FourGameteUtils.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(LIBCOMMON) $(LIBNET) $(LIBTREE) $(ARCH_ORTHOBJS) $(LIBEMBOSS) $(LIBLAV)
	$(CC) $(CCOPTS) $<  \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/ValidatedInversion.o \
	$(MACHTYPE)/FourGameteUtils.o \
	-o $@ $(LIBDIR) $(LIBS) -lemboss -lnet -ltree -llav -lblocks -lstdc++ 


$(MACHTYPE)/etadilav: $(MACHTYPE)/ValidateInversions.o \
	$(MACHTYPE)/InversionBins.o \
	 $(MACHTYPE)/InversionFile.o \
	$(MACHTYPE)/InversionDB.o \
	 $(MACHTYPE)/InversionUtils.o \
	 $(LIBCOMMON) $(LIBLAV) $(LIBBLOCKDB) $(LIBEMBOSS) $(LIBNET) $(LIBALIGN) $(LIBLAV)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/InversionDB.o \
	 $(MACHTYPE)/InversionFile.o \
	 $(MACHTYPE)/InversionUtils.o -o $@ $(LIBDIR) -llav -lblockdb -lemboss -lnet -lblock -lalign -llav $(MYSQL_LIB) $(LIBS) -lstdc++

$(MACHTYPE)/ordient: $(MACHTYPE)/OrderAndOrient.o $(LIBCOMMON) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ $(LIBDIR) -llav $(LIBS) -lstdc++

$(MACHTYPE)/findorder: $(MACHTYPE)/FindOrder.o $(LIBCOMMON) $(LIBLAV)
	$(CC) $(CCOPTS) $< -o $@ $(LIBDIR) -llav $(LIBS) -lstdc++

$(MACHTYPE)/loop: $(MACHTYPE)/LookupOrthoPos.o $(LIBCOMMON)
	$(CC) $(CCOPTS) $< -o $@  $(LIBDIR) -llav $(LIBS) -lstdc++

$(MACHTYPE)/fog: $(MACHTYPE)/FindOrthologousGaps.o $(LIBCOMMON) $(LIBBLOCKDB)
	$(CC) $(CCOPTS) $< -o $@  $(LIBDIR) -llav -lblockdb $(LIBS) $(MYSQL_LIB) -lstdc++

$(MACHTYPE)/lia: $(MACHTYPE)/LocateInversionAncestors.o \
	$(MACHTYPE)/CharTree.o \
	$(MACHTYPE)/InversionBins.o \
	$(MACHTYPE)/ValidatedInversion.o 
	$(CC) $(CCOPTS) $^ -o $@  $(LIBDIR) -lnet -lblocks -lcommon -ltree $(LIBS)   -lstdc++

$(MACHTYPE)/fsl: $(MACHTYPE)/FixSeqLengths.o $(LIBCOMMON) $(LIBBLOCKDB)
	$(CC) $(CCOPTS) $< -o $@  $(LIBDIR) $(LIBS) -llav -lblockdb  $(MYSQL_LIB)  -lstdc++

$(MACHTYPE)/grp: $(MACHTYPE)/GetRepeatPos.o $(LIBCOMMON) 
	$(CC) $(CCOPTS) $< -o $@  $(LIBDIR) $(LIBS) $(MYSQL_LIB)

$(MACHTYPE)/dbloop: $(MACHTYPE)/dbLookupOrthoPos.o \
	$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionBins.o \
	$(LIBCOMMON) $(LIBBLOCKDB) $(LIBNET) $(ARCH_ORTHOBJS) $(LIBEMBOSS)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionUtils.o	$(MACHTYPE)/InversionBins.o $(ARCH_ORTHOBJS) -o $@ $(LIBDIR)  -llav -lblockdb -lnet -lblocks -lemboss $(LIBS) \
	 $(MYSQL_LIB) -lstdc++

$(MACHTYPE)/dblap: $(MACHTYPE)/dbLookupAlignedPosition.o \
		$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionBins.o \
	$(LIBCOMMON) $(LIBBLOCKDB) $(ARCH_ORTHOBJS) $(LIBNET) $(LIBEMBOSS)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionUtils.o	$(MACHTYPE)/InversionBins.o $(ARCH_ORTHOBJS) -o $@  $(LIBDIR)  -llav -lblockdb -lnet -lblocks -lemboss $(LIBS) \
	 $(MYSQL_LIB) -lstdc++

$(MACHTYPE)/storient: $(MACHTYPE)/StoreOrientations.o  \
		$(MACHTYPE)/InversionUtils.o \
	$(MACHTYPE)/InversionBins.o \
	$(LIBCOMMON) $(LIBBLOCKDB) $(ARCH_ORTHOBJS) $(LIBNET)  $(LIBEMBOSS)
	$(CC) $(CCOPTS) $< $(MACHTYPE)/InversionUtils.o	$(MACHTYPE)/InversionBins.o $(ARCH_ORTHOBJS) -o $@  $(LIBDIR)  -llav -lblockdb -lnet -lblocks  -lemboss $(LIBS) \
	 $(MYSQL_LIB) -lstdc++

$(MACHTYPE)/winaln: $(MACHTYPE)/WindowAlign.o $(LIBCOMMON) $(LIBALIGN)
	$(CC) $(CCOPTS) $< -o $@  $(LIBDIR)  -llav $(LIBS) -lstdc++

$(LIBCOMMON):
	cd ../lib && ${MAKE} common

$(LIBNET):
	cd ../lib && ${MAKE} net

$(LIBTREE):
	cd ../lib && ${MAKE} tree
