name: SPAdes 1k test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix: 
        os: [ ubuntu-latest, macos-latest ]
#         os: [ macos-latest ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: compile
      run: assembler/spades_compile.sh -j3

    - name: multi-cell mode check
      run: bin/spades.py --test
    - name: single-cell mode check
      run: bin/spades.py --sc --test
    - name: plasmid mode check
      run: bin/plasmidspades.py --test
    - name: metagenomic mode check
      run: bin/metaspades.py --test
